### ISSUE TITLE
Can't Build For Android

### ISSUE THREAD

**Issue by Bananahavoc** [ua-i2cat/gst-unity-bridge#29]
Hey all,

I'm trying to compile this plugin as I'd like to contribute. I'm able to compile the Windows dlls with ease, but I can't seem to get the compiled Android version to work.

I'm using:
- NDK r10e
- Gstreamer 1.8 (both the arm and armv7 android versions)
- JDK 1.8.0_92

I've tried compiling on both Linux and Windows, and both complete. However, when I run the application with these new libraries, I get the error:

```
GUB: [Quad400] GStreamer encountered a general supporting library error. (gstamcvideodec.c(1013): _gl_sync_render_unlocked (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstAmcVideoDec-OmxExynosAvcDec:amcvideodec-omxexynosavcdec0:
E Unity   : Failed to call Java method: java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
E Unity   : java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
E Unity   :      at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E Unity   :      at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
```

After installing JDK/NDK, editing the gstreamer GST_GL_HAVE_GLSYNC to 1 in gstglconfig.h, and adding the GSTREAMER_ROOT_ANDROID environment variable, I run:

1. git clone <this-git-repo>
2. cd gst-unity-bridge/Plugin
3. android update project -p . -s --target android-23 (but I've tried 21 as well)
4. ndk-build

And then I copy these to my Unity project and overwrite the previous version, making sure that the library files are listed as armv7 in the inspector.

Does anyone have any ideas why the compiled android libraries are giving me that error? Are there any steps that I'm missing?

**Comment by Blindsp0t-creative** [comment]
Hi !
I'm getting exact same problem... 
"unable to update texture"

Did you manage to get rid of this ?

Thanks
